"""Declarative method definitions for the legacy registry."""
from __future__ import annotations

from core.method_registry_bindings import *  # noqa: F401,F403

PROCESSING_METHODS_BACKGROUND_DENOISE = {
    "subtracting_average_2D": {
            "name": "4 subtracting_average_2D (background removal)",
            "type": "core",
            "module": "subtracting_average_2D",
            "func": "subtracting_average_2D",
            "params": [
                {
                    "name": "ntraces",
                    "label": "Window traces",
                    "type": "int",
                    "default": 501,
                    "min": 1,
                    "max": 2001,
                },
                {
                    "name": "time_start_ns",
                    "label": "Time start (ns)",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 100000.0,
                    "tooltip": "背景抑制起始时间；0 表示从顶部开始。",
                },
                {
                    "name": "time_end_ns",
                    "label": "Time end (ns, 0=all)",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 100000.0,
                    "tooltip": "背景抑制结束时间；0 表示处理到剖面底部。",
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "background",
            "auto_tune_candidates": {
                "ntraces": [7, 11, 21, 31, 51, 81, 101, 151, 201, 301, 401, 501]
            },
        },
    "median_background_2D": {
            "name": "4.1 median_background_2D (median background removal)",
            "type": "local",
            "func": method_median_background_2d,
            "params": [
                {
                    "name": "ntraces",
                    "label": "Window traces",
                    "type": "int",
                    "default": 51,
                    "min": 1,
                    "max": 2001,
                },
                {
                    "name": "time_start_ns",
                    "label": "Time start (ns)",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 100000.0,
                    "tooltip": "背景抑制起始时间；0 表示从顶部开始。",
                },
                {
                    "name": "time_end_ns",
                    "label": "Time end (ns, 0=all)",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 100000.0,
                    "tooltip": "背景抑制结束时间；0 表示处理到剖面底部。",
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "background",
            "auto_tune_candidates": {
                "ntraces": [7, 11, 21, 31, 51, 81, 101, 151, 201, 301]
            },
        },
    "running_average_2D": {
            "name": "5 sharp clutter suppression",
            "type": "core",
            "module": "running_average_2D",
            "func": "running_average_2D",
            "params": [
                {
                    "name": "ntraces",
                    "label": "Window traces",
                    "type": "int",
                    "default": 9,
                    "min": 1,
                    "max": 2001,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "impulse",
            "auto_tune_candidates": {"ntraces": [3, 5, 7, 9, 11]},
        },
    "trace_median_filter": {
            "name": "道向中值滤波",
            "type": "local",
            "func": method_trace_median_filter,
            "params": [
                {
                    "name": "window_traces",
                    "label": "Window traces",
                    "type": "int",
                    "default": 5,
                    "min": 3,
                    "max": 501,
                    "tooltip": "沿道向的局部中值窗口；自动修正为不超过道数的奇数。",
                },
                {
                    "name": "preserve_mean",
                    "label": "Preserve global mean",
                    "type": "bool",
                    "default": False,
                    "tooltip": "保持全局均值，便于前后图像亮度对比；一般保持关闭。",
                },
            ],
            "auto_tune_enabled": False,
            "auto_tune_family": "denoise",
            "auto_tune_candidates": {"window_traces": [3, 5, 7, 9, 11]},
        },
    "trace_savgol_filter": {
            "name": "道向 Savitzky-Golay 平滑",
            "type": "local",
            "func": method_trace_savgol_filter,
            "params": [
                {
                    "name": "window_traces",
                    "label": "Window traces",
                    "type": "int",
                    "default": 7,
                    "min": 3,
                    "max": 501,
                    "tooltip": "沿道向的 Savitzky-Golay 平滑窗口；必须为奇数，系统会自动修正。",
                },
                {
                    "name": "polyorder",
                    "label": "Polynomial order",
                    "type": "int",
                    "default": 2,
                    "min": 1,
                    "max": 5,
                    "tooltip": "局部多项式阶数，必须小于窗口长度。",
                },
                {
                    "name": "mode",
                    "label": "Edge mode",
                    "type": "choice",
                    "default": "interp",
                    "choices": ["interp", "nearest", "mirror", "constant", "wrap"],
                    "tooltip": "边缘处理方式；常规使用 interp 或 nearest。",
                },
            ],
            "auto_tune_enabled": False,
            "auto_tune_family": "denoise",
            "auto_tune_candidates": {
                "window_traces": [5, 7, 9, 11, 15],
                "polyorder": [2, 3],
            },
        },
    "svd_bg": {
            "name": "SVD background removal (low-rank)",
            "type": "local",
            "func": method_svd_background,
            "params": [
                {
                    "name": "rank",
                    "label": "Rank (remove top r)",
                    "type": "int",
                    "default": 1,
                    "min": 1,
                    "max": 20,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "background",
            "auto_tune_candidates": {"rank": [1, 2, 3, 4, 5, 6, 8]},
        },
    "fk_filter": {
            "name": "F-K cone filter",
            "type": "local",
            "func": method_fk_filter,
            "params": [
                {
                    "name": "angle_low",
                    "label": "Stopband start angle (°)",
                    "type": "int",
                    "default": 12,
                    "min": 0,
                    "max": 90,
                },
                {
                    "name": "angle_high",
                    "label": "Stopband end angle (°)",
                    "type": "int",
                    "default": 55,
                    "min": 0,
                    "max": 90,
                },
                {
                    "name": "taper_width",
                    "label": "Taper width (°)",
                    "type": "int",
                    "default": 4,
                    "min": 0,
                    "max": 20,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "fk",
            "auto_tune_candidates": {
                "angle_low": [6, 8, 10, 12, 15, 18],
                "angle_high": [40, 48, 55, 62, 70, 78],
                "taper_width": [0, 2, 4, 6, 8],
            },
        },
    "frequency_filter_1d": {
            "name": "1D frequency filter",
            "type": "local",
            "func": method_frequency_filter_1d,
            "params": [
                {
                    "name": "filter_type",
                    "label": "滤波类型",
                    "type": "choice",
                    "choices": ["bandpass", "lowpass", "highpass", "notch"],
                    "default": "bandpass",
                },
                {
                    "name": "low_freq_mhz",
                    "label": "低截止频率 (MHz)",
                    "type": "float",
                    "default": 10.0,
                    "min": 0.0,
                    "max": 5000.0,
                },
                {
                    "name": "high_freq_mhz",
                    "label": "高截止频率 (MHz)",
                    "type": "float",
                    "default": 800.0,
                    "min": 0.0,
                    "max": 5000.0,
                },
                {
                    "name": "notch_freq_mhz",
                    "label": "陷波中心频率 (MHz)",
                    "type": "float",
                    "default": 50.0,
                    "min": 0.0,
                    "max": 5000.0,
                },
                {
                    "name": "notch_width_mhz",
                    "label": "陷波宽度 (MHz)",
                    "type": "float",
                    "default": 5.0,
                    "min": 0.0,
                    "max": 1000.0,
                },
                {
                    "name": "notch_depth",
                    "label": "陷波深度",
                    "type": "float",
                    "default": 1.0,
                    "min": 0.0,
                    "max": 1.0,
                },
                {
                    "name": "taper_ratio",
                    "label": "过渡带比例",
                    "type": "float",
                    "default": 0.08,
                    "min": 0.0,
                    "max": 0.5,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "frequency",
            "auto_tune_candidates": {
                "filter_type": ["bandpass"],
                "low_freq_mhz": [5.0, 10.0, 20.0, 40.0],
                "high_freq_ratio": [0.65, 0.75, 0.85, 0.95],
                "taper_ratio": [0.04, 0.08, 0.12],
            },
        },
    "hankel_svd": {
            "name": "Hankel SVD denoising",
            "type": "local",
            "func": method_hankel_svd,
            "params": [
                {
                    "name": "window_length",
                    "label": "Window length (0=auto bounded/literature, >0=fixed)",
                    "type": "int",
                    "default": 0,
                    "min": 0,
                    "max": 2000,
                },
                {
                    "name": "rank",
                    "label": "Rank kept (0=auto bounded/literature, >0=fixed)",
                    "type": "int",
                    "default": 0,
                    "min": 0,
                    "max": 100,
                },
                {
                    "name": "aggressiveness",
                    "label": "去噪激进程度 (0.1=保守, 2.0=激进)",
                    "type": "float",
                    "default": 0.5,
                    "min": 0.1,
                    "max": 2.0,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "denoise",
            "auto_tune_candidates": {
                "window_length": [0, 24, 32, 48, 64],
                "rank": [0, 1, 2, 3, 4, 5],
            },
        },
    "svd_subspace": {
            "name": "SVD子空间重构去噪",
            "type": "local",
            "func": method_svd_subspace,
            "params": [
                {
                    "name": "rank_start",
                    "label": "Start rank (1-based)",
                    "type": "int",
                    "default": 1,
                    "min": 1,
                    "max": 500,
                },
                {
                    "name": "rank_end",
                    "label": "End rank (1-based)",
                    "type": "int",
                    "default": 20,
                    "min": 1,
                    "max": 2000,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "denoise",
            "auto_tune_candidates": {
                "rank_start": [1, 2],
                "rank_end": [8, 12, 16, 20, 24, 32, 40],
            },
        },
    "wavelet_2d": {
            "name": "Wavelet 2D 去噪"
            + ("（需PyWavelets）" if not HAS_PYWAVELETS else ""),
            "type": "local",
            "func": _method_wavelet_2d,
            "params": [
                {
                    "name": "wavelet",
                    "label": "Wavelet",
                    "type": "str",
                    "default": "db4",
                },
                {
                    "name": "levels",
                    "label": "Levels",
                    "type": "int",
                    "default": 2,
                    "min": 1,
                    "max": 8,
                },
                {
                    "name": "threshold",
                    "label": "Threshold (0-1)",
                    "type": "float",
                    "default": 0.1,
                    "min": 0.0,
                    "max": 1.0,
                },
                {
                    "name": "threshold_strategy",
                    "label": "Threshold strategy",
                    "type": "str",
                    "default": "mad_universal",
                },
            ],
            "auto_tune_enabled": HAS_PYWAVELETS,
            "auto_tune_family": "denoise",
            "auto_tune_candidates": {
                "wavelet": ["db4"],
                "levels": [1, 2, 3],
                "threshold": [0.05, 0.08, 0.1, 0.12],
                "threshold_strategy": ["mad_universal"],
            },
        },
    "wavelet_svd": {
            "name": "Wavelet-SVD 复合去噪"
            + ("（需PyWavelets）" if not HAS_PYWAVELETS else ""),
            "type": "local",
            "func": _method_wavelet_svd,
            "params": [
                {
                    "name": "wavelet",
                    "label": "Wavelet",
                    "type": "str",
                    "default": "db4",
                },
                {
                    "name": "levels",
                    "label": "Levels",
                    "type": "int",
                    "default": 2,
                    "min": 1,
                    "max": 8,
                },
                {
                    "name": "threshold",
                    "label": "Threshold (0-1)",
                    "type": "float",
                    "default": 0.05,
                    "min": 0.0,
                    "max": 1.0,
                },
                {
                    "name": "threshold_strategy",
                    "label": "Threshold strategy",
                    "type": "str",
                    "default": "mad_universal",
                },
                {
                    "name": "rank_start",
                    "label": "Start rank (1-based)",
                    "type": "int",
                    "default": 1,
                    "min": 1,
                    "max": 500,
                },
                {
                    "name": "rank_end",
                    "label": "End rank (1-based)",
                    "type": "int",
                    "default": 20,
                    "min": 1,
                    "max": 2000,
                },
            ],
            "auto_tune_enabled": HAS_PYWAVELETS,
            "auto_tune_family": "denoise",
            "auto_tune_candidates": {
                "wavelet": ["db4"],
                "levels": [1, 2, 3],
                "threshold": [0.03, 0.05, 0.08],
                "threshold_strategy": ["mad_universal"],
                "rank_start": [1, 2],
                "rank_end": [8, 12, 16, 20, 24],
            },
        },
    "hilbert_envelope": {
            "name": "Hilbert envelope",
            "type": "local",
            "func": method_hilbert_envelope,
            "params": [
                {
                    "name": "normalize",
                    "label": "Normalize",
                    "type": "bool",
                    "default": False,
                },
                {
                    "name": "log_compress",
                    "label": "Log compress",
                    "type": "bool",
                    "default": False,
                },
            ],
        },
    "rpca_background": {
            "name": "RPCA背景抑制",
            "type": "local",
            "func": method_rpca_background,
            "params": [
                {
                    "name": "lam",
                    "label": "稀疏权重",
                    "type": "float",
                    "default": 0.08,
                    "min": 0.001,
                    "max": 1.0,
                },
                {
                    "name": "mu",
                    "label": "初始罚参数",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 10.0,
                },
                {
                    "name": "max_iter",
                    "label": "最大迭代次数",
                    "type": "int",
                    "default": 120,
                    "min": 10,
                    "max": 1000,
                },
                {
                    "name": "tol",
                    "label": "收敛阈值",
                    "type": "float",
                    "default": 1e-6,
                    "min": 1e-8,
                    "max": 1e-2,
                },
            ],
            "auto_tune_enabled": False,
        },
    "ccbs": {
            "name": "CCBS cross-correlation background subtraction",
            "type": "local",
            "func": method_ccbs,
            "params": [
                {
                    "name": "use_custom_ref",
                    "label": "Use custom reference wave",
                    "type": "bool",
                    "default": False,
                },
            ],
        },
}

__all__ = ["PROCESSING_METHODS_BACKGROUND_DENOISE"]
