"""Declarative method definitions for the legacy registry."""
from __future__ import annotations

from core.method_registry_bindings import *  # noqa: F401,F403

PROCESSING_METHODS_IMAGING = {
    "stolt_migration": {
            "name": "Stolt/ω-k 迁移（增强版）",
            "type": "local",
            "func": method_stolt_migration,
            "params": [
                {
                    "name": "dx",
                    "label": "道间距 dx (m)",
                    "type": "float",
                    "default": 0.05,
                    "min": 1e-4,
                    "max": 10.0,
                },
                {
                    "name": "dt",
                    "label": "时间步长 dt (ns)",
                    "type": "float",
                    "default": 0.1,
                    "min": 1e-5,
                    "max": 10.0,
                },
                {
                    "name": "v",
                    "label": "传播速度 v (m/ns)",
                    "type": "float",
                    "default": 0.10,
                    "min": 1e-4,
                    "max": 1.0,
                },
                {
                    "name": "pad_x",
                    "label": "横向补零倍数",
                    "type": "int",
                    "default": 1,
                    "min": 0,
                    "max": 8,
                },
                {
                    "name": "pad_t",
                    "label": "时间补零倍数",
                    "type": "int",
                    "default": 1,
                    "min": 0,
                    "max": 8,
                },
                {
                    "name": "stolt_jacobian_power",
                    "label": "Jacobian补偿幂次",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 1.0,
                },
                {
                    "name": "stolt_obliquity_power",
                    "label": "Obliquity补偿幂次",
                    "type": "float",
                    "default": 1.0,
                    "min": 0.0,
                    "max": 1.0,
                },
                {
                    "name": "stolt_mask_softness",
                    "label": "边缘软掩膜",
                    "type": "float",
                    "default": 0.03,
                    "min": 0.0,
                    "max": 0.3,
                },
                {
                    "name": "stolt_kz_smooth",
                    "label": "kz平滑窗口",
                    "type": "int",
                    "default": 3,
                    "min": 1,
                    "max": 15,
                },
                {
                    "name": "stolt_depth_gain",
                    "label": "深度增益系数",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 2.0,
                },
                {
                    "name": "stolt_depth_gain_power",
                    "label": "深度增益幂次",
                    "type": "float",
                    "default": 1.1,
                    "min": 0.5,
                    "max": 3.0,
                },
                {
                    "name": "stolt_clip_percentile",
                    "label": "幅值截断百分位",
                    "type": "float",
                    "default": 100.0,
                    "min": 95.0,
                    "max": 100.0,
                },
            ],
        },
    "kirchhoff_migration": {
            "name": "Kirchhoff 迁移",
            "type": "local",
            "func": method_kirchhoff_migration,
            "params": [
                {
                    "name": "freq",
                    "label": "中心频率 freq (Hz)",
                    "type": "float",
                    "default": 5.0e7,
                    "min": 1.0e6,
                    "max": 1.0e9,
                },
                {
                    "name": "depth",
                    "label": "成像深度 depth (m)",
                    "type": "float",
                    "default": 40.0,
                    "min": 0.1,
                    "max": 500.0,
                },
                {
                    "name": "v",
                    "label": "波速 v (m/ns)",
                    "type": "float",
                    "default": 0.10,
                    "min": 0.01,
                    "max": 1.0,
                },
                {
                    "name": "weight",
                    "label": "TV去噪权重",
                    "type": "float",
                    "default": 0.05,
                    "min": 0.0,
                    "max": 1.0,
                },
                {
                    "name": "alpha",
                    "label": "幂增益 alpha",
                    "type": "float",
                    "default": 1.0,
                    "min": 0.1,
                    "max": 3.0,
                },
                {
                    "name": "num_cal",
                    "label": "并行分块 num_cal",
                    "type": "int",
                    "default": 1,
                    "min": 1,
                    "max": 128,
                },
                {
                    "name": "hei_cor",
                    "label": "高度校正 hei_cor",
                    "type": "int",
                    "default": 0,
                    "min": 0,
                    "max": 2,
                },
                {
                    "name": "topo_cor",
                    "label": "地形校正 topo_cor",
                    "type": "int",
                    "default": 0,
                    "min": 0,
                    "max": 2,
                },
            ],
        },
    "time_to_depth": {
            "name": "深度转换与标定",
            "type": "local",
            "func": method_time_to_depth,
            "params": [
                {
                    "name": "dt",
                    "label": "时间步长 (ns)",
                    "type": "float",
                    "default": 0.1,
                    "min": 0.01,
                    "max": 10.0,
                },
                {
                    "name": "v",
                    "label": "波速 (m/ns)",
                    "type": "float",
                    "default": 0.10,
                    "min": 0.01,
                    "max": 0.3,
                },
                {
                    "name": "dz",
                    "label": "深度网格步长 (m)",
                    "type": "float",
                    "default": 0.02,
                    "min": 0.001,
                    "max": 1.0,
                },
            ],
        },
    "sec_gain": {
            "name": "SEC增益（深度补偿）",
            "type": "local",
            "func": method_sec_gain,
            "params": [
                {
                    "name": "gain_min",
                    "label": "增益下限",
                    "type": "float",
                    "default": 1.0,
                    "min": 0.1,
                    "max": 10.0,
                },
                {
                    "name": "gain_max",
                    "label": "增益上限",
                    "type": "float",
                    "default": 4.5,
                    "min": 0.1,
                    "max": 20.0,
                },
                {
                    "name": "power",
                    "label": "曲线幂次",
                    "type": "float",
                    "default": 1.1,
                    "min": 0.2,
                    "max": 3.0,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "gain",
            "auto_tune_candidates": {
                "gain_min": [1.0],
                "gain_max": [2.5, 3.5, 4.5, 5.5, 7.0, 9.0, 12.0],
                "power": [0.5, 0.8, 1.0, 1.2, 1.5, 1.8, 2.2],
            },
        },
    "sliding_avg": {
            "name": "Sliding-average background removal",
            "type": "local",
            "func": method_sliding_average,
            "params": [
                {
                    "name": "window_size",
                    "label": "Window size",
                    "type": "int",
                    "default": 10,
                    "min": 1,
                    "max": 200,
                },
                {
                    "name": "axis",
                    "label": "Axis (0/1)",
                    "type": "int",
                    "default": 1,
                    "min": 0,
                    "max": 1,
                },
            ],
        },
}

__all__ = ["PROCESSING_METHODS_IMAGING"]
