"""Declarative method definitions for the legacy registry."""
from __future__ import annotations

from core.method_registry_bindings import *  # noqa: F401,F403

PROCESSING_METHODS_MOTION = {
    "motion_compensation_height": {
            "name": "飞行高度归一化",
            "type": "local",
            "func": method_motion_compensation_height,
            "params": [
                {
                    "name": "reference_height_mode",
                    "label": "参考高度",
                    "type": "choice",
                    "choices": ["mean", "min", "manual"],
                    "default": "mean",
                },
                {
                    "name": "manual_height",
                    "label": "手动参考高度 (m)",
                    "type": "float",
                    "default": 10.0,
                    "min": 0.0,
                    "max": 500.0,
                },
                {
                    "name": "compensate_amplitude",
                    "label": "振幅校正",
                    "type": "bool",
                    "default": True,
                },
                {
                    "name": "compensate_time_shift",
                    "label": "时移校正",
                    "type": "bool",
                    "default": True,
                },
                {
                    "name": "height_source",
                    "label": "高度来源",
                    "type": "choice",
                    "choices": ["auto", "height_agl_m", "flight_height_m"],
                    "default": "auto",
                },
                {
                    "name": "wave_speed_m_per_ns",
                    "label": "传播速度假设 (m/ns)",
                    "type": "float",
                    "default": 0.299792458,
                    "min": 0.01,
                    "max": 1.0,
                    "tooltip": (
                        "UAV 空气路径高度时移建议使用 0.299792458；"
                        "若使用土壤等效速度需谨慎解释。"
                    ),
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "motion_comp",
            "auto_tune_candidates": {
                "reference_height_mode": ["mean", "min"],
                "height_source": ["auto"],
                "compensate_amplitude": [True, False],
                "compensate_time_shift": [True, False],
                "wave_speed_m_per_ns": [0.299792458],
            },
        },
    "motion_compensation_speed": {
            "name": "速度误差补偿",
            "type": "local",
            "func": method_motion_compensation_speed,
            "params": [
                {
                    "name": "spacing_m",
                    "label": "目标道间距 (m)",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 100.0,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "motion_comp",
            "auto_tune_candidates": {
                "spacing_m": [0.0],
            },
        },
    "trajectory_smoothing": {
            "name": "轨迹平滑",
            "type": "local",
            "func": method_trajectory_smoothing,
            "params": [
                {
                    "name": "method",
                    "label": "平滑方法",
                    "type": "choice",
                    "choices": ["savgol", "moving_average"],
                    "default": "savgol",
                },
                {
                    "name": "window_length",
                    "label": "窗口长度",
                    "type": "int",
                    "default": 21,
                    "min": 3,
                    "max": 501,
                },
                {
                    "name": "polyorder",
                    "label": "多项式阶数",
                    "type": "int",
                    "default": 3,
                    "min": 1,
                    "max": 7,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "motion_comp",
            "auto_tune_candidates": {
                "method": ["savgol"],
                "window_length": [11, 21, 31, 51],
                "polyorder": [2, 3],
            },
        },
    "motion_compensation_attitude": {
            "name": "姿态/APC足迹修正",
            "type": "local",
            "func": method_motion_compensation_attitude,
            "params": [
                {
                    "name": "apc_offset_x_m",
                    "label": "APC X偏移 (m)",
                    "type": "float",
                    "default": 0.0,
                    "min": -10.0,
                    "max": 10.0,
                },
                {
                    "name": "apc_offset_y_m",
                    "label": "APC Y偏移 (m)",
                    "type": "float",
                    "default": 0.0,
                    "min": -10.0,
                    "max": 10.0,
                },
                {
                    "name": "apc_offset_z_m",
                    "label": "APC Z偏移 (m)",
                    "type": "float",
                    "default": 0.0,
                    "min": -10.0,
                    "max": 10.0,
                },
                {
                    "name": "max_abs_tilt_deg",
                    "label": "最大允许倾角 (°)",
                    "type": "float",
                    "default": 20.0,
                    "min": 1.0,
                    "max": 90.0,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "motion_comp",
            "auto_tune_candidates": {
                "apc_offset_x_m": [0.0],
                "apc_offset_y_m": [0.0],
                "apc_offset_z_m": [0.0],
                "max_abs_tilt_deg": [15.0, 20.0, 30.0],
            },
        },
    "motion_compensation_vibration": {
            "name": "周期条带伪影抑制（实验）",
            "type": "local",
            "func": method_motion_compensation_vibration,
            "params": [
                {
                    "name": "smooth_window",
                    "label": "平滑窗口",
                    "type": "int",
                    "default": 9,
                    "min": 1,
                    "max": 101,
                },
                {
                    "name": "preserve_row_percentile",
                    "label": "保护行百分位",
                    "type": "float",
                    "default": 94.0,
                    "min": 50.0,
                    "max": 99.9,
                },
                {
                    "name": "preserve_mix",
                    "label": "保护混合系数",
                    "type": "float",
                    "default": 0.35,
                    "min": 0.0,
                    "max": 1.0,
                },
                {
                    "name": "background_mix",
                    "label": "背景混合系数",
                    "type": "float",
                    "default": 0.02,
                    "min": 0.0,
                    "max": 1.0,
                },
                {
                    "name": "max_restore_gain",
                    "label": "最大恢复增益",
                    "type": "float",
                    "default": 1.25,
                    "min": 1.0,
                    "max": 5.0,
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "denoise",
            "auto_tune_candidates": {
                "smooth_window": [5, 9, 15],
                "preserve_row_percentile": [90.0, 94.0, 98.0],
                "preserve_mix": [0.2, 0.35, 0.5],
                "background_mix": [0.0, 0.02, 0.05],
                "max_restore_gain": [1.1, 1.25, 1.5],
            },
        },
    "motion_compensation_v2": {
            "name": "UAV 运动补偿 V2",
            "type": "local",
            "func": method_motion_compensation_v2,
            "description": (
                "自动读取导入/传感器同步生成的 trace_metadata；"
                "界面只配置高度、重采样、APC 和安全阈值策略。"
            ),
            "params": [
                {
                    "name": "height_reference_mode",
                    "label": "参考高度",
                    "type": "choice",
                    "choices": ["mean", "min", "manual"],
                    "default": "mean",
                    "tooltip": "选择参考高度策略；manual 时才使用手动参考高度。",
                },
                {
                    "name": "manual_height_m",
                    "label": "手动参考高度 (m)",
                    "type": "float",
                    "default": 1.5,
                    "min": 0.01,
                    "max": 200.0,
                    "tooltip": "仅在参考高度=manual 时生效；逐道高度来自 trace_metadata。",
                },
                {
                    "name": "height_source",
                    "label": "高度来源",
                    "type": "choice",
                    "choices": ["auto", "height_agl_m", "flight_height_m"],
                    "default": "auto",
                    "tooltip": "选择 trace_metadata 中的高度字段；auto 优先使用 height_agl_m，必要时回退 flight_height_m。",
                },
                {
                    "name": "compensate_time_shift",
                    "label": "高度时移校正",
                    "type": "bool",
                    "default": True,
                    "tooltip": "根据逐道高度差做时间轴校正；逐道高度必须来自 sidecar 同步结果。",
                },
                {
                    "name": "compensate_amplitude",
                    "label": "高度振幅归一",
                    "type": "bool",
                    "default": True,
                    "tooltip": "按高度变化做幅值归一，受最大振幅倍率保护。",
                },
                {
                    "name": "max_shift_samples",
                    "label": "最大时移样点 (0=按时间窗)",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 500.0,
                    "tooltip": "安全阈值；0 表示主要按 max_shift_ns 和采样时间窗换算。",
                },
                {
                    "name": "max_shift_ns",
                    "label": "最大时移时间 (ns)",
                    "type": "float",
                    "default": 20.0,
                    "min": 0.0,
                    "max": 200.0,
                    "tooltip": "安全阈值；限制高度时移的物理时间范围。",
                },
                {
                    "name": "max_amplitude_scale",
                    "label": "最大振幅倍率",
                    "type": "float",
                    "default": 2.0,
                    "min": 1.0,
                    "max": 20.0,
                    "tooltip": "安全阈值；防止高度归一导致幅值过度放大。",
                },
                {
                    "name": "resample_spacing_m",
                    "label": "等距重采样间距 (m, 0=自动)",
                    "type": "float",
                    "default": 0.0,
                    "min": 0.0,
                    "max": 10.0,
                    "tooltip": "0 表示自动使用当前 trace_distance_m 的中位间距；输入正数表示手动目标道距。",
                },
                {
                    "name": "apc_offset_x_m",
                    "label": "APC X偏移 (m)",
                    "type": "float",
                    "default": 0.0,
                    "min": -5.0,
                    "max": 5.0,
                    "tooltip": "设备配置中的相位中心 X 偏移，可按实测标定修正。",
                },
                {
                    "name": "apc_offset_y_m",
                    "label": "APC Y偏移 (m)",
                    "type": "float",
                    "default": 0.0,
                    "min": -5.0,
                    "max": 5.0,
                    "tooltip": "设备配置中的相位中心 Y 偏移，可按实测标定修正。",
                },
                {
                    "name": "apc_offset_z_m",
                    "label": "APC Z偏移 (m)",
                    "type": "float",
                    "default": 0.0,
                    "min": -5.0,
                    "max": 5.0,
                    "tooltip": "设备配置中的相位中心 Z 偏移，可按实测标定修正。",
                },
                {
                    "name": "max_abs_tilt_deg",
                    "label": "最大姿态角 (deg)",
                    "type": "float",
                    "default": 20.0,
                    "min": 0.1,
                    "max": 89.0,
                    "tooltip": "安全阈值；超过该姿态角的道会产生质量告警或被限制。",
                },
            ],
            "auto_tune_enabled": True,
            "auto_tune_family": "motion_comp",
            "auto_tune_candidates": {
                "height_reference_mode": ["mean", "min"],
                "compensate_amplitude": [True, False],
                "max_amplitude_scale": [1.5, 2.0, 3.0],
                "resample_spacing_m": [0.0],
            },
        },
}

__all__ = ["PROCESSING_METHODS_MOTION"]
