[pytest]
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore:Please import `gaussian_filter` from the `scipy\.ndimage` namespace:DeprecationWarning
    ignore:Glyph .* missing from font\(s\) DejaVu Sans:UserWarning
