"""Display, maturity, category, and auto-tune metadata for processing methods."""
from __future__ import annotations

METHOD_METADATA = {
    "compensatingGain": {
        "category": "gain",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "增益补偿",
    },
    "dewow": {
        "category": "drift_correction",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "低频漂移矫正（Dewow）",
    },
    "set_zero_time": {
        "category": "time_correction",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "零时矫正",
    },
    "time_cut": {
        "category": "time_correction",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "时间窗裁剪",
    },
    "trace_qc": {
        "category": "quality_control",
        "maturity": "stable",
        "visibility": "hidden",
        "display_name": "坏道质量控制",
    },
    "equidistant_trace_resample": {
        "category": "quality_control",
        "maturity": "stable",
        "visibility": "hidden",
        "display_name": "等距道重采样",
    },
    "agcGain": {
        "category": "gain",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "自动增益控制（AGC）",
    },
    "energy_decay_gain": {
        "category": "gain",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "能量衰减增益",
    },
    "amplitude_scale": {
        "category": "gain",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "幅值缩放/归一化",
    },
    "subtracting_average_2D": {
        "category": "background_suppression",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "平均背景抑制",
    },
    "median_background_2D": {
        "category": "background_suppression",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "中值背景抑制",
    },
    "running_average_2D": {
        "category": "denoising",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "道向运行平均平滑",
    },
    "trace_median_filter": {
        "category": "denoising",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "道向中值滤波",
    },
    "trace_savgol_filter": {
        "category": "denoising",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "道向 Savitzky-Golay 平滑",
    },
    "svd_bg": {
        "category": "background_suppression",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "SVD 背景抑制",
    },
    "fk_filter": {
        "category": "filtering",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "F-K 频波数滤波",
    },
    "frequency_filter_1d": {
        "category": "filtering",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "一维频域滤波",
    },
    "hankel_svd": {
        "category": "denoising",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "Hankel-SVD 去噪",
    },
    "svd_subspace": {
        "category": "denoising",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "SVD 子空间去噪",
    },
    "wavelet_2d": {
        "category": "denoising",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "Wavelet 2D 去噪",
    },
    "wavelet_svd": {
        "category": "denoising",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "Wavelet-SVD 复合去噪",
    },
    "hilbert_envelope": {
        "category": "attribute_analysis",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "Hilbert 包络",
    },
    "rpca_background": {
        "category": "background_suppression",
        "maturity": "experimental",
        "visibility": "hidden",
        "display_name": "RPCA 背景抑制",
    },
    "ccbs": {
        "category": "background_suppression",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "互相关背景抑制（CCBS）",
    },
    "motion_compensation_height": {
        "category": "motion_compensation",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "飞行高度归一化",
    },
    "motion_compensation_speed": {
        "category": "motion_compensation",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "速度误差补偿",
    },
    "trajectory_smoothing": {
        "category": "motion_compensation",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "轨迹平滑",
    },
    "motion_compensation_attitude": {
        "category": "motion_compensation",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "姿态/APC足迹修正",
    },
    "motion_compensation_vibration": {
        "category": "artifact_suppression",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "周期条带伪影抑制（实验）",
    },
    "motion_compensation_v2": {
        "category": "motion_compensation",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "UAV 运动补偿 V2",
        "description": "Unified motion compensation V2. Per-trace sensor values come from trace_metadata, not manual input.",
    },
    "stolt_migration": {
        "category": "migration",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "Stolt 迁移",
    },
    "kirchhoff_migration": {
        "category": "migration",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "Kirchhoff 迁移",
    },
    "time_to_depth": {
        "category": "depth_conversion",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "时间-深度转换",
    },
    "sec_gain": {
        "category": "gain",
        "maturity": "stable",
        "visibility": "public",
        "display_name": "SEC 增益",
    },
    "sliding_avg": {
        "category": "background_suppression",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "滑动平均背景抑制",
    },
    "rtm_migration": {
        "category": "migration",
        "maturity": "experimental",
        "visibility": "public",
        "display_name": "RTM 反向时间迁移",
    },
}

PREFERRED_METHOD_ORDER = [
    "set_zero_time",
    "time_cut",
    "trace_qc",
    "equidistant_trace_resample",
    "dewow",
    "subtracting_average_2D",
    "median_background_2D",
    "svd_bg",
    "ccbs",
    "sliding_avg",
    "frequency_filter_1d",
    "fk_filter",
    "sec_gain",
    "energy_decay_gain",
    "amplitude_scale",
    "compensatingGain",
    "agcGain",
    "hankel_svd",
    "trace_median_filter",
    "trace_savgol_filter",
    "svd_subspace",
    "wavelet_2d",
    "wavelet_svd",
    "hilbert_envelope",
    "running_average_2D",
    "motion_compensation_vibration",
    "motion_compensation_height",
    "motion_compensation_speed",
    "trajectory_smoothing",
    "motion_compensation_attitude",
    "motion_compensation_v2",
    "stolt_migration",
    "kirchhoff_migration",
    "rtm_migration",
    "time_to_depth",
]

METHOD_TAGS = {
    "subtracting_average_2D": "推荐",
    "median_background_2D": "备选",
    "agcGain": "备选",
    "dewow": "推荐",
    "set_zero_time": "推荐",
    "time_cut": "备选",
    "trace_qc": "备选",
    "equidistant_trace_resample": "备选",
    "energy_decay_gain": "推荐",
    "amplitude_scale": "备选",
    "svd_bg": "备选",
    "fk_filter": "实验",
    "frequency_filter_1d": "推荐",
    "hankel_svd": "实验",
    "svd_subspace": "实验",
    "wavelet_2d": "实验",
    "wavelet_svd": "实验",
    "hilbert_envelope": "推荐",
    "stolt_migration": "实验",
    "kirchhoff_migration": "实验",
    "rtm_migration": "实验",
    "sliding_avg": "实验",
    "running_average_2D": "备选",
    "trace_median_filter": "备选",
    "trace_savgol_filter": "备选",
    "motion_compensation_height": "实验",
    "motion_compensation_speed": "实验",
    "trajectory_smoothing": "实验",
    "motion_compensation_attitude": "实验",
    "motion_compensation_vibration": "实验",
    "motion_compensation_v2": "推荐",
}

METHOD_CATEGORY_LABELS = {
    "time_correction": "时间校正",
    "drift_correction": "低频漂移矫正",
    "background_suppression": "背景抑制",
    "clutter_suppression": "杂波抑制",
    "filtering": "频域/频波数滤波",
    "denoising": "去噪",
    "gain": "增益",
    "migration": "迁移成像",
    "depth_conversion": "时间深度转换",
    "motion_compensation": "运动补偿",
    "artifact_suppression": "伪影抑制",
    "quality_control": "质量控制",
    "attribute_analysis": "属性分析",
    "experimental": "实验功能",
}

AUTO_TUNE_STAGE_BY_METHOD = {
    "set_zero_time": "zero_time",
    "time_cut": "preprocess",
    "trace_qc": "preprocess",
    "equidistant_trace_resample": "preprocess",
    "dewow": "drift",
    "subtracting_average_2D": "background",
    "median_background_2D": "background",
    "svd_bg": "background",
    "fk_filter": "frequency",
    "frequency_filter_1d": "frequency",
    "ccbs": "background",
    "sec_gain": "gain",
    "energy_decay_gain": "gain",
    "amplitude_scale": "gain",
    "compensatingGain": "gain",
    "agcGain": "gain",
    "running_average_2D": "impulse",
    "hankel_svd": "denoise",
    "trace_median_filter": "denoise",
    "trace_savgol_filter": "denoise",
    "svd_subspace": "denoise",
    "wavelet_2d": "denoise",
    "wavelet_svd": "denoise",
    "motion_compensation_height": "motion_comp",
    "motion_compensation_speed": "motion_comp",
    "trajectory_smoothing": "motion_comp",
    "motion_compensation_attitude": "motion_comp",
    "motion_compensation_vibration": "artifact",
    "motion_compensation_v2": "motion_comp",
    "rtm_migration": "migration",
}

METHOD_DISPLAY_NAMES = {key: value["display_name"] for key, value in METHOD_METADATA.items()}

__all__ = [
    "METHOD_METADATA",
    "METHOD_DISPLAY_NAMES",
    "PREFERRED_METHOD_ORDER",
    "METHOD_TAGS",
    "METHOD_CATEGORY_LABELS",
    "AUTO_TUNE_STAGE_BY_METHOD",
]
